@startuml
actor User
participant Client as ui
participant Server as app
participant BoardUtils
participant SBPClient
participant SBPMessageFormat
participant SBPServerController
participant BoardController
participant BoardService
participant BoardRepository
participant Database

alt
User -> ui: choose Share Board
activate ui
ui -> ui: ShareBoard(client, board, users)
activate ui
deactivate ui
end alt
ui -> SBPClient: startConnection()
deactivate ui
activate SBPClient
SBPClient -> SBPClient: sendShareBoardRequest(board, users)
activate SBPClient
deactivate SBPClient
SBPClient -> SBPMessageFormat: toByteArray()
deactivate SBPClient
activate SBPMessageFormat
SBPMessageFormat -> SBPClient: requestbytes
deactivate SBPMessageFormat
activate SBPClient
SBPClient -> app: sendRequest()
deactivate SBPClient
activate app
app -> SBPServerController: fromByteArray()
deactivate app
activate SBPServerController
SBPServerController -> SBPMessageFormat: fromByteArray(message)
deactivate SBPServerController
activate SBPMessageFormat
SBPMessageFormat -> SBPServerController: getData()
deactivate SBPMessageFormat
activate SBPServerController
SBPServerController -> BoardController: shareBoard(board, users)
deactivate SBPServerController
activate BoardController
BoardController -> BoardService: shareBoard(board, users)
deactivate BoardController
activate BoardService
BoardService -> Board: shareBoard(board, users)
deactivate BoardService
activate Board
Board -> BoardService: board shared
deactivate Board
activate BoardService
BoardService -> BoardRepository: save(board)
deactivate BoardService
activate BoardRepository
BoardRepository -> Database: persist board
deactivate BoardRepository
activate Database
Database -> BoardRepository: board saved
deactivate Database
activate BoardRepository
BoardRepository -> BoardService: board saved
deactivate BoardRepository
activate BoardService
BoardService -> BoardController: board saved
deactivate BoardService
activate BoardController
BoardController -> SBPServerController: sendAcknowledgeResponse()
deactivate BoardController
activate SBPServerController
SBPServerController -> app: sendResponse()
deactivate SBPServerController
activate app
app -> SBPClient: responsebytes
deactivate app
activate SBPClient
SBPClient -> ui: board shared
deactivate SBPClient
activate ui
ui -> User: board shared
deactivate ui
@enduml